sudo: required

language: generic

services:
- docker

script:
- docker run --rm -e PHP_EXTENSION_INTL=1 -v "$PWD":/usr/src/app thecodingmachine/php:7.2-v1-cli composer install
- docker run --rm -e PHP_EXTENSION_INTL=1 -v "$PWD":/usr/src/app thecodingmachine/php:7.2-v1-cli composer run cs-check
- docker run --rm -e PHP_EXTENSION_INTL=1 -v "$PWD":/usr/src/app thecodingmachine/php:7.2-v1-cli composer run phpstan
- docker build . -t theaentmachine/aent-docker-compose:snapshot